
Declare @price float= 7.39
Declare @psku varchar(20)= '68748748'
Declare @pstruc varchar(4)='0001'
SELECT * from PRICE_STRUCTURE where sku=@psku

Update company_PRICE_STRUCTURE set 
  PRICE_UNIT3=@price,
  EFFECTIVE_DATE= '20211001',
  PRICE_UNIT1=(select sell_factor1 from sku where sku=@psku)*@price, 
  PRICE_UNIT2=(select sell_factor2 from sku where sku=@psku) *@price, 
  EFFECTIVE_TODATE= CAST('20501231' AS datetime)
where sku=@psku and PRICE_STRUC=@pstruc
update company_PRICE_STRUCTURE set 
  PRICE_STANDARD=PRICE_UNIT1, RPRICE_UNIT1=PRICE_UNIT1, 
  RPRICE_UNIT2=PRICE_UNIT2, RPRICE_UNIT3=PRICE_UNIT3,RPRICE_STANDARD=PRICE_UNIT1,GPRICE_UNIT1=PRICE_UNIT1, 
  GPRICE_UNIT2=PRICE_UNIT2, GPRICE_UNIT3=PRICE_UNIT3, GRPRICE_UNIT1=PRICE_UNIT1, GRPRICE_UNIT2=PRICE_UNIT2, 
  GRPRICE_UNIT3=PRICE_UNIT3, Commission=0, PRICE_PURCHASE1=PRICE_UNIT1, PRICE_PURCHASE2=PRICE_UNIT2, 
  PRICE_PURCHASE3=PRICE_UNIT3, GPRICE_PURCHASE1=PRICE_UNIT1, GPRICE_PURCHASE2=PRICE_UNIT2, GPRICE_PURCHASE3=PRICE_UNIT3, 
  SED=0, MRSP=0, FMR=0, UNLOADING_CHARGES=0, SPECIAL_DISCOUNT=0, FOODSERVICE_DISCOUNT=0, DIS_BUILDING_ALLOWANCE=0,
  GST_REGISTERED=15, GST_NREGISTERED=15
  
  select * from company_price_structure where sku=@psku