USE [centegy_sndpro_uet]
GO

/****** Object:  Table [dbo].[IG_CONFIGURATION]    Script Date: 5/10/2023 12:13:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IG_CONFIGURATION](
	[PARAMETER_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PARAMETER_ACCOUNT] [nvarchar](max) NULL,
	[PARAMETER_NAME] [nvarchar](max) NULL,
	[PARAMETER_DESCRIPTION] [nvarchar](max) NULL,
	[PARAMETER_VALUE_STRING] [nvarchar](max) NULL,
	[PARAMETER_VALUE_DATETIME] [datetime] NULL,
	[PARAMETER_VALUE_INTEGER] [int] NULL,
	[PARAMETER_SOURCE] [nvarchar](max) NULL,
	[PARAMETER_TYPE] [nvarchar](max) NULL,
	[PARAMETER_REGEX] [nvarchar](max) NULL,
	[IS_READ_ONLY] [bit] NULL,
 CONSTRAINT [PK_IG_CONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[PARAMETER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


