ALTER DATABASE centegy_sndpro_uet SET EMERGENCY;
GO
ALTER DATABASE Centegy_sndpro_uet SET SINGLE_USER;
Go
DBCC CHECKDB (centegy_sndpro_uet, REPAIR_ALLOW_DATA_LOSS) WITH NO_INFOMSGS, ALL_ERRORMSGS;
GO
ALTER DATABASE centegy_sndpro_uet SET ONLINE
go
ALTER DATABASE Centegy_sndpro_uet SET MULTI_USER;