USE centegy_sndpro_uet
Declare @copiedsku varchar(20)='68748752' 
Declare @newSku varchar(20)='68909738'   
Declare @pstruc varchar(4)='0001'

insert into PRICE_STRUCTURE
	(company, sku, PRICE_STRUC, EFFECTIVE_DATE, PRICE_UNIT1,PRICE_UNIT2,PRICE_UNIT3,DISTRIBUTOR,EFFECTIVE_TODATE, PRICE_STANDARD, RPRICE_UNIT1,RPRICE_UNIT2,
	RPRICE_UNIT3,RPRICE_STANDARD,GPRICE_UNIT1, GPRICE_UNIT2, GPRICE_UNIT3, GRPRICE_UNIT1, GRPRICE_UNIT2, GRPRICE_UNIT3, Commission, PRICE_PURCHASE1,
	PRICE_PURCHASE2, PRICE_PURCHASE3, GPRICE_PURCHASE1, GPRICE_PURCHASE2, GPRICE_PURCHASE3, SED, MRSP, FMR, UNLOADING_CHARGES, SPECIAL_DISCOUNT, 
	FOODSERVICE_DISCOUNT, DIS_BUILDING_ALLOWANCE,GST_REGISTERED, GST_NREGISTERED)
select 
	COMPANY=COMPANY, SKU=@newSku, PRICE_STRUCTURE=@pstruc,
	EFFECTIVE_DATE= (select WORKING_DATE from distributor), 
	PRICE_UNIT1= PRICE_UNIT1, PRICE_UNIT2= PRICE_UNIT2, PRICE_UNIT3=PRICE_UNIT3,
	DISTRIBUTOR=(select DISTRIBUTOR from distributor), EFFECTIVE_TODATE= CAST('20501231' AS datetime),
	PRICE_STANDARD=PRICE_STANDARD, RPRICE_UNIT1=RPRICE_UNIT1, 
	RPRICE_UNIT2=RPRICE_UNIT2, RPRICE_UNIT3=RPRICE_UNIT3,RPRICE_STANDARD=RPRICE_STANDARD,GPRICE_UNIT1=GPRICE_UNIT1, 
	GPRICE_UNIT2=GPRICE_UNIT2, GPRICE_UNIT3=gPRICE_UNIT3, GRPRICE_UNIT1=GRPRICE_UNIT1, GRPRICE_UNIT2=GRPRICE_UNIT2, 
	GRPRICE_UNIT3=GRPRICE_UNIT3, Commission=Commission, PRICE_PURCHASE1=PRICE_PURCHASE1, PRICE_PURCHASE2=PRICE_PURCHASE2, 
	PRICE_PURCHASE3=PRICE_PURCHASE3, GPRICE_PURCHASE1=GPRICE_PURCHASE1, GPRICE_PURCHASE2=GPRICE_PURCHASE2, GPRICE_PURCHASE3=GPRICE_PURCHASE3, 
	SED=SED, MRSP=MRSP, FMR=FMR, UNLOADING_CHARGES=UNLOADING_CHARGES, SPECIAL_DISCOUNT=SPECIAL_DISCOUNT, FOODSERVICE_DISCOUNT=FOODSERVICE_DISCOUNT, 
	DIS_BUILDING_ALLOWANCE=DIS_BUILDING_ALLOWANCE,
	GST_REGISTERED=15, GST_NREGISTERED=15 FROM PRICE_STRUCTURE
where sku=@copiedsku and PRICE_STRUC=@pstruc

SELECT * from PRICE_STRUCTURE where sku in (@copiedsku,@newSku)