IF OBJECT_ID('MIS_KPI_DATA_700') IS NULL
CREATE TABLE [dbo].[MIS_KPI_DATA_700](
	[COMPANY] [varchar](10) NOT NULL,
	[DISTRIBUTOR] [varchar](10) NOT NULL,
	[YEAR] [varchar](4) NOT NULL,
	[JCNO] [varchar](10) NOT NULL,
	[ECO] [numeric](18, 2) NULL,
	[ASSORTMENT] [numeric](18, 2) NULL,
	[ROW_DELETED] [int] NULL,
	[ROW_VER] [timestamp] NOT NULL,
	[IROW_VER]  AS (CONVERT([bigint],[ROW_VER],(0))) PERSISTED,
 CONSTRAINT [PK_MIS_KPI_DATA_700] PRIMARY KEY CLUSTERED 
(
	[COMPANY] ASC,
	[DISTRIBUTOR] ASC,
	[YEAR] ASC,
	[JCNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]