IF OBJECT_ID('PERIOD_CALENDAR') IS NULL
CREATE TABLE [dbo].[PERIOD_CALENDAR](
	[COMPANY] [varchar](10) NOT NULL,
	[CALENDER_TYPE] [varchar](10) NOT NULL,
	[CALENDER_ID] [varchar](10) NOT NULL,
	[DESCRIPTION] [varchar](100) NULL,
	[START_DATE] [datetime] NOT NULL,
	[END_DATE] [datetime] NOT NULL,
	[YEAR] [varchar](4) NULL,
	[JCNO] [varchar](2) NULL,
	[ROW_VER] [timestamp] NOT NULL,
	[IROW_VER]  AS (CONVERT([bigint],[ROW_VER],(0))) PERSISTED,
 CONSTRAINT [PK_PERIOD_CALENDAR] PRIMARY KEY CLUSTERED 
(
	[COMPANY] ASC,
	[CALENDER_TYPE] ASC,
	[CALENDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO