use centegy_sndpro_uet
GO

select * from POP_TYPE
select * from APPLICATION_SETUP WHERE PARAMETER_ID = 'SD_POP_TYPE'
select * from LOCATION
select VALUE_COMB,* from DISTRIBUTOR_ASSOCIATION WHERE  FIELD_COMB = 'MASTER_DISTRIBUTOR_LOCATION_CODE'
select * from BATCH_TASK where TASK_ID='DA_BASEDON_CM'
select * from BATCH_SCHEDULE where TASK_ID='DA_BASEDON_CM'