USE Centegy_sndpro_uet
DECLARE @PJP VARCHAR(4)='A001'
DECLARE @COPYPJP VARCHAR(4)='B001'

INSERT INTO PJP_DETAIL
(COMPANY,DISTRIBUTOR,pjp,SELL_CATEGORY,SECTION,WEEK_NO,SAT,SUN,MON,TUE,WED,THU,FRI,REF_PJP)
 SELECT COMPANY,DISTRIBUTOR,@PJP,'001',SECTION,WEEK_NO,SAT,SUN,MON,TUE,WED,THU,FRI,@PJP FROM PJP_DETAIL
 WHERE pjp=@COPYPJP