USE CENTEGY_SNDPRO_PRO
select t.sku, t.doc_NO, T.DOCUMENT,T.ENTRY_TYPE,T.BATCH, T.WAREHOUSE, T.REF_QTY1, T.REF_QTY2, T.REF_QTY3, GD.REF_QTY1, GD.REF_QTY2,GD.REF_QTY3 from trans_detail t
inner join GIN_DETAIL gd on gd.DOC_NO=t.DOC_NO and t.sku=gd.SKU
where t.sku=68842513 and t.DOC_DATE >='20220224' 


UPDATE TRANS_DETAIL SET REF_QTY1= (SELECT REF_QTY1 from GIN_DETAIL where sku=t.SKU and DOC_NO=t.DOC_NO and SR_NO=1 ) , 
REF_QTY2= (SELECT REF_QTY3 from GIN_DETAIL where sku=t.sku and DOC_NO=g.DOC_NO and  DOC_DATE = g.DOC_DATE  and SR_NO=1) ,  
REF_QTY3= (SELECT REF_QTY1 from GIN_DETAIL where sku=t.sku and DOC_NO=g.DOC_NO and DOC_DATE = g.DOC_DATE  and SR_NO=1) 
FROM TRANS_DETAIL T
INNER JOIN GIN_DETAIL G ON G.DOC_NO=T.DOC_NO AND G.DOCUMENT=T.DOCUMENT AND T.BATCH=G.BATCH  
WHERE T.sku=68842513 and g.sr_no=1 and t.DOC_DATE between '20220224' and '20220227'
