EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all";
EXEC sp_msforeachtable "ALTER TABLE ? DISABLE TRIGGER all";

/*SELECT 'UPDATE '+TABLE_NAME+' SET '+COLUMN_NAME+' = RIGHT(''00''+'+COLUMN_NAME+',2);' FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME IN ('JCNO','WEEK_NO') AND DATA_TYPE LIKE '%VARCHAR'*/

UPDATE JC_WEEK SET JCNO = RIGHT('00'+JCNO,2);
UPDATE J_CYCLE SET JCNO = RIGHT('00'+JCNO,2);
UPDATE DL_JC_Week SET JCNO = RIGHT('00'+JCNO,2);
UPDATE SUGGESTED_ORDER_DETAIL SET JCNO = RIGHT('00'+JCNO,2);
UPDATE BrandTarget_Brand SET JCNO = RIGHT('00'+JCNO,2);
UPDATE Audit_J_CYCLE SET JCNO = RIGHT('00'+JCNO,2);
UPDATE Audit_JC_WEEK SET JCNO = RIGHT('00'+JCNO,2);
UPDATE STOCK_BATCH_QAMAR SET JCNO = RIGHT('00'+JCNO,2);
UPDATE DSR_Productivity_Benchmarks SET jcno = RIGHT('00'+jcno,2);
UPDATE Distributor_Productivity_Benchmarks SET jcno = RIGHT('00'+jcno,2);
UPDATE Expense_Detail SET JCNO = RIGHT('00'+JCNO,2);
UPDATE FCS_SUMMARY_DATA SET JCNO = RIGHT('00'+JCNO,2);
UPDATE FCS_SUMMARY_DSR_DATA SET JCNO = RIGHT('00'+JCNO,2);
UPDATE FCS_SUMMARY_DSR_SC_DATA SET JCNO = RIGHT('00'+JCNO,2);
UPDATE FCS_SUMMARY_DSR_SE_DATA SET JCNO = RIGHT('00'+JCNO,2);
UPDATE FCS_SUMMARY_SE_DATA SET JCNO = RIGHT('00'+JCNO,2);
UPDATE SKUTarget_Brand SET JCNO = RIGHT('00'+JCNO,2);
UPDATE STOCKCOMPARISON SET JCNO = RIGHT('00'+JCNO,2);
UPDATE STOCK_BATCH SET JCNO = RIGHT('00'+JCNO,2);
UPDATE Stock_Batch_Log SET JCNO = RIGHT('00'+JCNO,2);
UPDATE JC_WEEK SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE DL_JC_Week SET Week_No = RIGHT('00'+Week_No,2);
UPDATE SUGGESTED_ORDER_DETAIL SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE SKUTARGET SET Week_no = RIGHT('00'+Week_no,2);
UPDATE BrandTarget SET Week_no = RIGHT('00'+Week_no,2);
UPDATE Audit_JC_WEEK SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE STOCK_BATCH_QAMAR SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE FCS_SUMMARY_DATA SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE FCS_SUMMARY_DSR_DATA SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE FCS_SUMMARY_DSR_SC_DATA SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE FCS_SUMMARY_DSR_SE_DATA SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE FCS_SUMMARY_SE_DATA SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE POP_LEDGER SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE STOCK_BATCH SET WEEK_NO = RIGHT('00'+WEEK_NO,2);
UPDATE Stock_Batch_Log SET WEEK_NO = RIGHT('00'+WEEK_NO,2);

exec sp_msforeachtable "ALTER TABLE ? ENABLE TRIGGER all";
EXEC sp_msforeachtable "ALTER TABLE ?  CHECK CONSTRAINT all";
