DELETE FROM AC_GL_SM_SUBMASTER WHERE PPD_PERDNO=0 and PCA_GLACCODE='01020020001'
-- DELETE ALL OPENING BALANCES
delete FROM AC_GL_MR_MASTER WHERE PPD_PERDNO=0 and PCA_GLACCODE='01020020001'

-- INSERT IN MASTER TABLE OF OPENING BALANCES.
INSERT INTO AC_GL_MR_MASTER(POR_ORGACODE,PLC_LOCACODE,PPF_PRFCCODE,PCA_GLACCODE,LMR_MASTACTBGTREV,PFS_ACNTYEAR,PPT_PTYPCODE,PPD_PERDNO,PCR_CURRCODE
,LMR_MASTBALDRFC,LMR_MASTBALCRFC,LMR_MASTBALDRBC,LMR_MASTBALCRBC)
SELECT COMPANY,DISTRIBUTOR,PROFIT_CENTER,ACCOUNT_CODE, ENTRY_TYPE,YEAR,PERIOD_TYPE,PERIOD,CURRENCY_CODE, SUM(DEBIT_OPENING_BALANCE) DEBIT_OPENING_BALANCE,SUM(CREDIT_OPENING_BALANCE) CREDIT_OPENING_BALANCE,SUM(DEBIT_OPENING_BALANCE1) DEBIT_OPENING_BALANCE1,SUM(CREDIT_OPENING_BALANCE1) CREDIT_OPENING_BALANCE1    
FROM
(
SELECT C.COMPANY,C.DISTRIBUTOR,'0000' PROFIT_CENTER,'01020020001' ACCOUNT_CODE,'AC' ENTRY_TYPE,CAST(YEAR(C.DOC_DATE) AS VARCHAR)+CAST(YEAR(C.DOC_DATE) AS VARCHAR) YEAR,'0004' PERIOD_TYPE,0 PERIOD,'001' CURRENCY_CODE
, SUM(ISNULL(C.NET_AMOUNT,0)-ISNULL(C.RECEIVED_AMT,0)) DEBIT_OPENING_BALANCE,0 CREDIT_OPENING_BALANCE,SUM(ISNULL(C.NET_AMOUNT,0)-ISNULL(C.RECEIVED_AMT,0))  DEBIT_OPENING_BALANCE1,0 CREDIT_OPENING_BALANCE1  FROM CASHMEMO C 
WHERE C.DOC_NO NOT IN(SELECT DOC_NO FROM CASHMEMO_DETAIL) 
GROUP BY C.COMPANY,C.DISTRIBUTOR,C.DOC_DATE
HAVING SUM(ISNULL(C.NET_AMOUNT,0)-ISNULL(C.RECEIVED_AMT,0)) > 0
)DT
GROUP BY COMPANY,DISTRIBUTOR,PROFIT_CENTER,ACCOUNT_CODE, ENTRY_TYPE,YEAR,PERIOD_TYPE,PERIOD,CURRENCY_CODE ;


-- DELETE DETAIL OPENING BALANCES
DELETE FROM AC_GL_SM_SUBMASTER WHERE PPD_PERDNO=0 and PCA_GLACCODE='01020020001'
-- INSERT IN DETEIL TABLE OF OPENING BALANCES.
INSERT INTO AC_GL_SM_SUBMASTER	(POR_ORGACODE,PLC_LOCACODE,PPF_PRFCCODE,PCA_GLACCODE,LMR_MASTACTBGTREV,PFS_ACNTYEAR,PPT_PTYPCODE,PPD_PERDNO,PSP_STYPCODE,PSA_SACTACCOUNT,PCR_CURRCODE,LSM_SMSTBALDRFC,LSM_SMSTBALCRFC,LSM_SMSTBALDRBC,LSM_SMSTBALCRBC)
SELECT COMPANY,DISTRIBUTOR,PROFIT_CENTER,ACCOUNT_CODE, ENTRY_TYPE,YEAR,PERIOD_TYPE,PERIOD,PSP_STYPCODE,PSA_SACTACCOUNT,CURRENCY_CODE, SUM(DEBIT_OPENING_BALANCE) DEBIT_OPENING_BALANCE,SUM(CREDIT_OPENING_BALANCE) CREDIT_OPENING_BALANCE,SUM(DEBIT_OPENING_BALANCE1) DEBIT_OPENING_BALANCE1,SUM(CREDIT_OPENING_BALANCE1) CREDIT_OPENING_BALANCE1    
FROM
(
SELECT C.COMPANY,C.DISTRIBUTOR,'0000' PROFIT_CENTER,'01020020001' ACCOUNT_CODE,'AC' ENTRY_TYPE,CAST(YEAR(C.DOC_DATE) AS VARCHAR)+CAST(YEAR(C.DOC_DATE) AS VARCHAR) YEAR,'0004' PERIOD_TYPE,0 PERIOD,'0002' PSP_STYPCODE,P.fin_subledger PSA_SACTACCOUNT,
'001' CURRENCY_CODE, SUM(ISNULL(C.NET_AMOUNT,0)-ISNULL(C.RECEIVED_AMT,0)) DEBIT_OPENING_BALANCE,0 CREDIT_OPENING_BALANCE,SUM(ISNULL(C.NET_AMOUNT,0)-ISNULL(C.RECEIVED_AMT,0))  DEBIT_OPENING_BALANCE1,0 CREDIT_OPENING_BALANCE1 


FROM CASHMEMO C 
INNER JOIN POP P ON C.COMPANY=P.COMPANY AND C.DISTRIBUTOR=P.DISTRIBUTOR AND C.TOWN=P.TOWN AND C.LOCALITY=P.LOCALITY AND C.SLOCALITY=P.SLOCALITY AND C.POP=P.POP
WHERE C.DOC_NO NOT IN(SELECT DOC_NO FROM CASHMEMO_DETAIL) 
GROUP BY C.COMPANY,C.DISTRIBUTOR,C.DOC_DATE,P.fin_subledger
HAVING SUM(ISNULL(C.NET_AMOUNT,0)-ISNULL(C.RECEIVED_AMT,0)) > 0
)DT


GROUP BY COMPANY,DISTRIBUTOR,PROFIT_CENTER,ACCOUNT_CODE, ENTRY_TYPE,YEAR,PERIOD_TYPE,PERIOD,PSP_STYPCODE,PSA_SACTACCOUNT,CURRENCY_CODE;



