
delete from AC_GL_SM_SUBMASTER
go
delete from AC_GL_SB_SUBDETAIL
go






---- MAKE FIN_SUBLEDGER AS THE FIELD TO BE USED FOR CREATiON OF SUB LEDGERS
UPDATE POP SET FIN_SUBLEDGER = (select value_comb+POP.PREV_POP_CODE from DISTRIBUTOR_ASSOCIATION
where FIELD_COMB='DIST_SRNO' and isnumeric(value_comb)=1 ) where FIN_SUBLEDGER is null
Go

--Map latest POPs (by their Prev_POP_Code) into Subledger Accounts
delete from PR_GL_SA_SUBACCOUNTS where PSP_STYPCODE='0002'
go
INSERT INTO PR_GL_SA_SUBACCOUNTS (POR_ORGACODE,PSP_STYPCODE,PSA_SACTACCOUNT,PSA_SACTDESC,PSA_SACTAGING,PSA_SACTACTIVE)
SELECT COMPANY,'0002',FIN_SUBLEDGER,NAME,'Y','Y' FROM POP;




