delete from ACCH_ChartOfAccount
delete from ACCH_COALevel
delete from ACCH_SQL_STATEMENT
delete from ACCH_Transaction
delete from ACCOUNT_GROUP
delete from Activity_Detail
delete from Activity_Head
delete from Activity_Transaction
delete from ALLOCATED_STOCK
delete from ALLOWANCE_DEDUCTION
delete from ALLOWANCE_DEDUCTION_DETAIL
delete from Asset
delete from ASSET_CENSUS
delete from ASSET_CENSUS_TYPE
delete from ASSET_OPERATION_STATUS
delete from ASSET_PAYMENT
delete from ASSET_QUOTA
delete from ASSET_QUOTA_TYPE
delete from ASSET_SERVICE
delete from ASSET_SERVICE_PLAN
delete from ASSET_TRACKING_STATUS
delete from AssetBarCode
delete from AssetCategory
delete from AssetComplaint
delete from AssetPart
delete from AssetRank
delete from ASSETREPAIR
delete from AssetStatus
delete from AssetStatusHistory
delete from AssetTransaction
delete from AssetTransactonReason
delete from AssetType
delete from AVAIL_TYPE
delete from AVLVSL_DETAIL
delete from BrandTarget
delete from BrandTarget_Brand
delete from BrandValueVolume
delete from CABIN
delete from CABIN_PRODUCT
delete from CATEGORY
delete from Category_Distribution
delete from CLAIM_SUB_TYPE
delete from CompanyWareHouse
delete from COMPETITOR
delete from COMPETITOR_DETAIL
delete from COMPETITOR_PRODUCTS
delete from ComplaintStatus
delete from ComplaintType
delete from CONTAINER
delete from CONTRACT_DETAIL
delete from CONTRACT_HEAD
delete from CONTRACT_RANGE
delete from CONVERSION_STATUS
delete from CSD_STATUS
delete from CUSTOMERHIERARCHY
delete from DESCRIPTION_DETAIL
delete from DESCRIPTION_HEAD
delete from DEVICE_HOME_SCREEN
delete from Distributor_Productivity_Benchmarks
delete from DISTRIBUTOR_RA_MAPPING
delete from DISTRIBUTOR_SERVINGTOWN
delete from DISTRIBUTOR_SKUQTY
delete from DISTRIBUTOR_VISITTYPE
delete from DSR_MANAGER
delete from DSR_Productivity_Benchmarks
delete from EMP_ALL_DED_DETAIL
delete from EMPLOYEE
delete from EMPLOYEE_ALLOWANCE_DEDUCTION
delete from EMPLOYEE_ATTENDANCE
delete from EMPLOYEE_EDUCATION
delete from Employee_EOJ_Reason
delete from EMPLOYEE_EXPERIENCE
delete from EMPLOYEE_INCENTIVE
delete from EMPLOYEE_SALARY
delete from EMPLOYEE_STATUS
delete from Expense_Detail
delete from FCS_LPPC_BENCHMARK
delete from FCS_SUB_ELEMENT_TARGET
delete from FCS_SUMMARY_DATA
delete from FCS_SUMMARY_DSR_DATA
delete from FCS_SUMMARY_DSR_SC_DATA
delete from FCS_SUMMARY_DSR_SE_DATA
delete from FCS_SUMMARY_SE_DATA
delete from focusedpjp
delete from FOCUSSEDSKU
delete from FUEL_RECEIPT
delete from GADGET_DETAIL
delete from GADGET
delete from GADGET_POP_STATUS
delete from GADGET_TRANSACTION
delete from GADGET_TYPE
delete from IMAGECAPTURE
delete from INCENTIVE_POP_Adjustment_Detail
delete from INCENTIVE_POP_TRANSACTION
delete from INCENTIVE_SCHEME_POP
delete from INCENTIVE_SCHEME_DETAIL
delete from INCENTIVE_SCHEME_MASTER
delete from INCENTIVE_DETAIL
delete from INCENTIVE_FOR
delete from INCENTIVE_HEAD
delete from INCENTIVE_MASTER
delete from INCENTIVE_SLAB
delete from INCENTIVE_TYPE
delete from Interface_POP_Adjustment_Detail
delete from INTERFACE_DETAIL
delete from INTERFACE_MASTER
delete from INTERFACE_POP_TRANSACTION
delete from INTERFACE_SCHEME_DETAIL
delete from INTERFACE_SCHEME_MASTER
delete from INTERFACE_SCHEME_POP
delete from INVOICE_CLAIM
delete from INVOICE_DETAIL
delete from INVOICE_HEAD
delete from IO_NUMBER
delete from MARKET_ACTIVITY
delete from MARKET_ACTIVITY_DETAIL
delete from masterskuassortment
delete from MERGE_SKU_DETAIL
delete from MERGE_SKU_HEAD
delete from NEW_SKU
delete from open_cash
delete from OUTLET_HIERARCHY_LSR2
delete from OUTLET_HIERARCHY_LSW
delete from PD_BaseInfo
delete from PD_Description
delete from PD_POPDefinition
delete from PD_POPTargetTotal
delete from PD_SKU
delete from PD_SKUTYPE
delete from PJPSKU_ALLOCATION
delete from PLANOGRAM
delete from PLANOGRAM_DETAIL
delete from PLANOGRAM_REC
delete from PLANOGRAM_REC_DTL
delete from POP_AGREEMENT_RECEIPT_DETAIL
delete from POP_AGREEMENT_RECEIPT
delete from pop_device
delete from POP_DISCOUNT
delete from POP_DISCOUNT_REQUEST
delete from POP_DISCOUNT_REQUEST_LOG
delete from POP_DISCOUNT_TRANSACTION
delete from POP_DISTRIBUTOR_MAPPING
delete from POP_HANDLER
delete from POP_MASTER
delete from POP_MERCHANDIZING
delete from POP_PROD1_INFO
delete from previous_town
delete from Price_formula
delete from RANK_POLICY
delete from RANK_POLICY_DETAIL
delete from RECEIPT_TYPE
delete from RED_AGREEMENT_DETAIL
delete from RED_AGREEMENT_HEAD
delete from RED_AGREMENT_MASTER
delete from REFERENCEDSKU
delete from REINDEX_SHRINK_LOG
delete from RepairShop
delete from [RESOURCE]
delete from RESOURCE_TYPE
delete from SALE_GROUP
delete from SAM_DETAIL
delete from SAM_HEAD
delete from sch_pop
delete from SCREEN
delete from SECTION_SKUQTY
delete from SenderReceiverLocation
delete from sku_device
delete from SKUTARGET
delete from SKUTarget_Brand
delete from SSC_Category
delete from SSC_Category_POP
delete from SSC_PRICECOMPLIANCE
delete from SSC_PRICECOMPLIANCE_TRANS
delete from SSC_PRODLAUN_TRANS
delete from SSC_PRODUCTLAUNCH
delete from SSC_Ques_TRANS
delete from SSC_Questions
delete from SSC_SubCategory
delete from STG_AVLVSL_DETAIL
delete from STG_CASHMEMO
delete from STG_CASHMEMO_DETAIL
delete from STG_DEPOSIT_SLIP
delete from STG_DEPOSIT_SLIP_DETAIL
delete from STG_POP_SCHEME_EXCEPT
delete from STG_RECEIPT_DETAIL_SKU
delete from STG_RECEIPT_HEAD
delete from STG_SCHEME_DISCOUNT
delete from STG_SCHEME_DISCOUNT_DETAIL
delete from STG_SCHEME_SKU
delete from STOCKCOMPARISON
delete from TEMP_POP_STATUS
delete from tempflds
delete from USERS_PASS_HIS
